/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import java.util.ArrayList;
import java.util.Iterator;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public class RetrieveRecords extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		EmpJB e=new EmpJB();
		
		String en=request.getParameter("eno");

		System.out.println("stirng:"+en);
	
		System.out.println("getRecords() is going called");
		ArrayList list=e.getRecords(en);
		Iterator i=list.iterator();
		while(i.hasNext()){
			
			Object o=i.next();
			System.out.println(o);
			Emp ee=(Emp)o;
			System.out.println(ee.getEno());
			System.out.println(ee.getName());
			System.out.println(ee.getSalary());
			request.setAttribute("eno",ee.getEno());
			request.setAttribute("name",ee.getName());
			request.setAttribute("salary",ee.getSalary());
	   	}
		return mapping.findForward("success1");
	}
}